[workspace]
authors = ["hyzhou"]
channels = ["conda-forge"]
name = "HUGSIM"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.11.10"
setuptools = "==78.1.0"

[pypi-dependencies]
torch = { version = "==2.4.1", index = "https://download.pytorch.org/whl/cu118" }
torchvision = { version = "==0.19.1", index = "https://download.pytorch.org/whl/cu118"}
torchmetrics = ">=1.7.1, <2"
